#pragma once
enum TiposDeToken
{	
	UNDEF,	//INDEFINIDO 0
	ID,		//IDENTIFICADOR 1
	INTEGER_LITERAL,//INTEIRO 3

	OP,		//OPERADORES 4
		SUM,	//SOMA 5
		DIF,	//SUBTRAÇÃO 6
		MULT,	//MULTIPLICAÇÃO 7
		DIV,	//DIVISÃO 8
		MOD,	//RESTO 9
		REC,	//ATRIBUIÇÃO 10

	RELOP, //OPERADOR RELACIONAL 11
		MN,		//MENOR 12
		MA,		//MAIOR 13
		MNE,	//MENOR IGUAL 14
		MAE,	//MAIOR IGUAL 15
		EQ,		//IGUALDADE 16
		NEQ,	//!IGUALDADE 17
	
	STR,	//STRING 18
	
	SEP,	//SEPARADORES 19
		EPAR,	//PARENTESE ESQUERDO 20
		DPAR,	//PARENTESE DIREITO 21
		ECOL,	//COLCHETE ESQUERDO 22
		DCOL,	//COLCHETE DIREITO 23
		ECHAV,	//CHAVE ESQUERDA 24
		DCHAV,	//CHAVE DIREITA 25
		PVIR, 	//PONTO E VIRGULA 26
		PNT, 	//PONTO 27
		VIR,	//VIRGULA 28

	END_OF_FILE, //FIM DE ARQUIVO 29
	

	RESERV,//PALAVRAS RESERVADAS 30
		CLASS, 	//CLASS 31
		EXTND, 	//EXTENDS 32
		INT, 	//INT 33
		STRING, //STRING 34
		BRK, 	//BREAK 35
		PRT,	//PRINT 36
		READ,	//READ 37
		RTN,	//RETURN 38
		SPR,	//SUPER 39
		IF,		//IF 40
		ELSE,	//ELSE 41
		FOR,	//FOR 42
		NEW,	//NEW 43
		CNST,	//CONSTRUTOR 44
};
